### ISSUE TITLE
Error parsing PR2 description

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#23]
@Hi @afonsocastro ,

I have an error when I launch create_first_guess.py using the PR2.

```bash
Unknown attribute "type" in /robot[@name='pr2']/link[@name='base_laser_link']
Unknown attribute "name" in /robot[@name='pr2']/link[@name='torso_lift_link']/collision[1]
Unknown tag "simulated_actuated_joint" in /robot[@name='pr2']/transmission[@name='torso_lift_trans']
Unknown attribute "type" in /robot[@name='pr2']/link[@name='wide_stereo_optical_frame']
Unknown attribute "type" in /robot[@name='pr2']/link[@name='narrow_stereo_optical_frame']
Unknown attribute "type" in /robot[@name='pr2']/link[@name='laser_tilt_link']
Unknown tag "compensator" in /robot[@name='pr2']/transmission[@name='r_shoulder_pan_trans']
Unknown tag "compensator" in /robot[@name='pr2']/transmission[@name='r_shoulder_lift_trans']
Traceback (most recent call last):
  File "/home/mike/catkin_ws/src/AtlasCarCalibration/interactive_marker_test/src/create_first_guess.py", line 102, in <module>
    xml_robot = URDF.from_parameter_server()
  File "/home/mike/catkin_ws/src/urdf_parser_py/src/urdf_parser_py/urdf.py", line 667, in from_parameter_server
    return cls.from_xml_string(rospy.get_param(key))
  File "/home/mike/catkin_ws/src/urdf_parser_py/src/urdf_parser_py/xml_reflection/core.py", line 612, in from_xml_string
```

Do you have the same problem?

**Comment by miguelriemoliveira** [comment]
The problem I think is related to this 

https://github.com/ros/urdfdom/issues/36

**Comment by miguelriemoliveira** [comment]
I was trying to make this work all day and could not do it. 

As a backup solution, I am now using **pr2_no_arms.urdf.xacro** which works because the problem was in an element of the arms.

**Comment by miguelriemoliveira** [comment]
Same as #19. Closing this one.
