### ISSUE TITLE
collect_and_label crashes with error

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#89]
Hi @tiagomfmadeira , 

I think this is something you did, I remember you talking about contours. Strange how your cv findcountours is diferent from mine ... what open / python are you using?

We have python 2.7 

```
[ERROR] [1576107710.598549, 1575573639.793589]: bad callback: <bound method InteractiveDataLabeler.sensorDataReceivedCallback of <interactive_calibration.interactive_data_labeler.InteractiveDataLabeler instance at 0x7f2fd61b0050>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/mike/catkin_ws/src/AtlasCarCalibration/interactive_calibration/src/interactive_calibration/interactive_data_labeler.py", line 162, in sensorDataReceivedCallback
    self.labelData()  # label the data
  File "/home/mike/catkin_ws/src/AtlasCarCalibration/interactive_calibration/src/interactive_calibration/interactive_data_labeler.py", line 352, in labelData
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack
```

**Comment by miguelriemoliveira** [comment]
Hi @tiagomfmadeira ,

found this 
https://stackoverflow.com/questions/25504964/opencv-python-valueerror-too-many-values-to-unpack

and changed the line to 

`_,contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`

works for me, will commit, try to see if it works for you.

**Comment by miguelriemoliveira** [comment]
Hi @tiagomfmadeira this is solved right? If so please close ...

**Comment by miguelriemoliveira** [comment]
Closed without feedback : - (
